name: CI

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build & Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 20.x
      - name: Build
        working-directory: ./packages/app/default
        #run: yarn --skip-integrity-check --no-lockfile --network-timeout 100000
        run: yarn --immutable --network-timeout 100000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
      #- name: Check for uncommitted changes in yarn.lock
      #  run: |
      #    if git diff --name-only | grep -q "^yarn.lock"; then
      #      echo "::error::The yarn.lock file has uncommitted changes!"
      #      exit 1
      #    fi
      #- name: Create eslint json report
      #  run: |
      #    yarn lint:ci

      #- name: Create summary
      #  run: |
      #    npm_config_yes=true npx github:10up/eslint-json-to-md#82ff16b --path ./eslint_report.json --output ./eslint_report.md
      #   cat eslint_report.md >> $GITHUB_STEP_SUMMARY
      - name: Build all Modules
        run: yarn run build
        env:
          NODE_OPTIONS: --max_old_space_size=65536

      - name: Build browser
        working-directory: ./packages/app/default
        run: yarn run build:prod
        env:
          NODE_OPTIONS: --max_old_space_size=65536

      - name: Cache Build Output
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ./packages/app/default/dist
          key: build-cache-${{ github.sha }}
